---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app: $APP_NAME
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
        - name: quarkus
          image: docker.io/$REGISTRY_USER_NAME/$APP_IMAGE
          env:
           - name: QUARKUS_DATASOURCE_URL
             value: "jdbc:mariadb://mariadb/demodb"
          ports:
            - name: http-web
              containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
